# PLEASE OPEN NYU CLASSES

# Log into Jupyterhub
***

# Here is the Plan!

## <u> Itinerary: </u>

1. Bools!
2. Lists!
3. Importing Packages
4. Numpy
5. Start Lab 1# Big week, lots to do:


# 1. <u> Bools </u>

## Bools are another data type

## True and False are bools

## Essentially, python can do basic logic for us. Let's see. 

In [1]:
True

True

In [2]:
type(True)

bool

In [3]:
type(False)

bool

## We get Bools when we ask python to evaluate something

In [4]:
5 < 10

True

In [5]:
5 > 10

False

In [6]:
a = 20
b = 13

a > b

True

In [7]:
c = 13

b > c

False

In [8]:
b >= c

True

In [9]:
b == c

True

## Notice! We used '==' and not '='. 

## '==' is evaluation (is this true?)

## '=' is assignment!

## How to check is somethis is not equal?


In [10]:
a != b

True

In [11]:
a

20

In [13]:
b != c

False

## Notice, we can assign the outcome of an evaluation to a variable

In [14]:
outcome = a > b

In [15]:
outcome

True

In [16]:
outcome2 = (a == b)

In [18]:
print(outcome2)

False


In [19]:
type(outcome)


bool

## We will use these alot more

# 2. <u> Lists! </u>

## Lists are a datatype that can hold, store or otherwise be a place to put other data!

 <img src="lists.jpeg">
 
 Let's create a list

In [20]:
my_list = []

In [21]:
my_list

[]

### my_list is an empty list. 

### you create lists with SQUARE brackets, i.e., [ and ]

### Things are seperated in lists by commas

In [24]:
my_list2 = [1,23,4]

In [25]:
my_list2

[1, 23, 4]

### my_list2 is a list, with three items, all of which are integers.

### Lists can store ANY object, and they don't all have to be the same type

In [26]:
mix_list = [8,5.0,'5.0']

In [27]:
mix_list

[8, 5.0, '5.0']

### What if we want to get one item out of a list?

### For example, what if we wanted to get the float 5.0 from mix_list?

### Lists are <u> ordered.</u>  Python will always remember the order of the elements in a list (this is not true of some other data types)

### So all we have to do to get a specific item from a list, is tell python which number item we want.

### How do we do that?

### For lists, we just tell python the index of the item in list, i.e., whatever number it is.

### BUT, python doesn't count 1,2,3,4. 

### Python indexs from 0. Python counts 0,1,2,3,4.

### That means 5.0 is indexed to 1 (not 2), while 8 is indexed to 0

# Remeber, indexing starts at 0 (NOT 1)

 <img src="index.png">

## So how do we tell python, give us element 1 (the SECOND element) from mix_list? (or any list)

In [28]:
mix_list

[8, 5.0, '5.0']

In [29]:
mix_list[1]

5.0

In [30]:
mix_list[0]

8

In [31]:
mix_list[2]

'5.0'

In [32]:
mix_list[5]

IndexError: list index out of range

### Ok, so now we can get at the items in lists, and we can assign those values to new variables

In [33]:
elem_2 = mix_list[2]

In [36]:
elem_2 == mix_list[2]

True

In [35]:
mix_list

[8, 5.0, '5.0']

## We can ALSO select multiple value at once with a slice

In [37]:
mix_list

[8, 5.0, '5.0']

In [38]:
mix_list[0:2]

[8, 5.0]

## In a slice, the first element in INCLUSIVE, and then it includes all elements, except the list one.

## Let's see

In [48]:
big_list = ['a','b','c','d','e','f','g','h']
big_list

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [40]:
big_list[2:5]

['c', 'd', 'e']

In [49]:
mix_list == mix_list

True

## Neat trick -- In order to get the LAST item, use -1 

In [41]:
big_list[-1]

'h'

In [42]:
big_list[-2]

'g'

### Can we change elements in the list? Yes, yes we can!

### Lists are mutable (changable), but note that not all datatpyes are!

In [43]:
mix_list

[8, 5.0, '5.0']

In [50]:
mix_list[2] ="A different string"

In [51]:
mix_list

[8, 5.0, 'A different string']

### How do we tell how long is? i.e., how many elements are in a list?

### Use len(), len stands for length!

In [52]:
len(mix_list)

3

### Finally, there are some built in functions that work on lists that have only numbers (integers and floats)

### They are max(), min() and mean() and they do what they say they do!

In [60]:
number_list = [423,35.0,1, 76]

In [61]:
sum(number_list)

535.0

In [62]:
min(number_list)

1

In [63]:
max(number_list)

423

### How do we find the mean or average?

In [64]:
sum(number_list)/len(number_list)

133.75

### How do we add to a list? .append()

In [65]:
new_list = []

In [66]:
new_list

[]

In [67]:
new_list.append(1)

In [68]:
new_list

[1]

In [69]:
new_list.append(2)

In [70]:
new_list

[1, 2]

In [71]:
new_list.append([1,2])

In [72]:
new_list

[1, 2, [1, 2]]

### Append only adds ONE THING at a time, so appending a list to a list, adds the whole thing as one item!

In [73]:
new_list[-1]

[1, 2]

In [74]:
new_list[-1][0]

1

 ## To add one item at time, we use .extend()

In [75]:
new_list

[1, 2, [1, 2]]

In [76]:
new_list.extend([1,2])

In [77]:
new_list

[1, 2, [1, 2], 1, 2]

## We can also remove items using the del (for delete) command

In [78]:
big_list

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [95]:
del big_list[2]

In [96]:
big_list

['a', 'b', 'g', 'h']

## Finally, we can remove items using .remove()

## But we have to specify the item

In [89]:
new_list = [1, 2, [1, 2], 1, 2]

new_list.remove(1)
new_list.remove(1)

In [90]:
new_list

[2, [1, 2], 2]

In [91]:
new_list.remove(1)

ValueError: list.remove(x): x not in list

In [97]:
check_list = [1,2,3,4,2]

In [98]:
check_list.remove(2)

In [99]:
check_list

[1, 3, 4, 2]

# 4 <u> Numpy </u>

## Numpy stands for numerical python.

### Its an outside package that gives us lots and lots of convenient ways to work with data

### If you've ever worked with vectors, matrices, or linear algebra, numpy is basically how we work with those things

### If you don't know those things, no worries!

### Before we can use numpy we have to import it

In [100]:
import numpy as np

### Basically, we import numpy, but we ask python to abbreviate it to np (for convience)

### Whenever we want to use some functions from numpy, we just start with np

### For now, all we want to use are numpy arrays

### Arrays are alot like lists, but they are designed to work with numbers

### Here is how we create one

In [103]:
my_arr = np.array([1,2,3])

In [104]:
new_list = [1,2,3]
new_arr = np.array(new_list)


In [105]:
print(my_arr)

[1 2 3]


In [106]:
my_arr

array([1, 2, 3])

In [107]:
type(my_arr)

numpy.ndarray

### We call numpy, call the array function, and then pass it a list of numbers

### And we can do cool stuff with it

In [108]:
my_arr*5

array([ 5, 10, 15])

In [109]:
my_arr**3

array([ 1,  8, 27])

In [110]:
num_list = [1,2]
num_list*5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

### This is very different than if we just did this to a normal list

In [112]:
num_list = [1,2,3]

In [113]:
num_list*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

### We even get more functionality

### numpy has a mean function (np.mean())

In [111]:
np.mean(my_arr)

2.0

# Alright, let's get started on lab One